name: GitHub Actions Demo
on: [push]
jobs:
  Ubuntu-hello-world-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls
      - name: List files in the repository
        run: cd ${{ github.workspace }}
      - name: Get C++ environment
        run: ls