name: GitHub Actions Demo
on: [push]
jobs:
  Ubuntu-hello-world-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Get C++ environment
        run: sudo apt-get install g++ -y
      - name: compile main.cpp
        run: g++ ${{ github.workspace }}/main.cpp -o main
      - name: run main
        run: ./main
      - uses: actions/upload-artifact@v3
        with:
          name: hello-world
          path: main
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Windows-hello-world-release:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: compile main.cpp
        run: g++ ${{ github.workspace }}\\main.cpp -o ${{ github.workspace }}\\main.exe
      - name: run main
        run: ${{ github.workspace }}\\main.exe
      - uses: actions/upload-artifact@v3
        with:
          name: hello-world
          path: ${{ github.workspace }}\\main.exe
      - run: echo "🍏 This job's status is ${{ job.status }}."
