name: GitHub Actions Demo
on: [push]
jobs:
  Ubuntu-hello-world-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Get C++ environment
        run: apt-get install g++ -y
      - name: compile main.cpp
        run: g++ ${{ github.workspace }}/main.cpp -o main
      - run: echo "🍏 This job's status is ${{ job.status }}."
